# Generated by Django 5.1.3 on 2025-07-26 17:51

import base.base_upload_handlers
import base.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file_name",
                    models.CharField(max_length=50, verbose_name="File Name"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=base.base_upload_handlers.handle_medical_document,
                        validators=[
                            base.utils.validate_medical_document_extension,
                            base.base_upload_handlers.handle_medical_document_upload_limit,
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "belonging_department",
                    models.CharField(
                        choices=[
                            ("CARDIOLOGY", "Cardiology"),
                            ("NEUROLOGY", "Neurology"),
                            ("ORTHOPEDICS", "Orthopedics"),
                            ("RADIOLOGY", "Radiology"),
                            ("GENERAL", "General"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Select the department this document is associated with.",
                        max_length=50,
                        verbose_name="Belonging Department",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Note"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
                (
                    "uploaded_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="documents_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded To",
                    ),
                ),
            ],
            options={
                "verbose_name": "MedicalDocument",
                "verbose_name_plural": "MedicalDocuments",
            },
        ),
    ]
