# Generated by Django 5.1.3 on 2025-07-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicaldocument",
            name="file_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="File Name"
            ),
        ),
    ]
