# Generated by Django 5.1.3 on 2024-11-24 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=100, null=True, verbose_name='EndPoint')),
                ('response_code', models.PositiveSmallIntegerField(verbose_name='Response Code')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, null=True, verbose_name='Method')),
                ('remote_address', models.GenericIPAddressField(null=True, verbose_name='IP Address')),
                ('exec_time', models.IntegerField(null=True, verbose_name='Execution Time In Millisecond')),
                ('body_response', models.TextField(verbose_name='Body Response')),
                ('body_request', models.TextField(verbose_name='Body Request')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Is Mobile')),
                ('is_touch_capable', models.BooleanField(default=False, verbose_name='Is Touch Capable')),
                ('is_tablet', models.BooleanField(default=False, verbose_name='Is Tablet')),
                ('is_pc', models.BooleanField(default=False, verbose_name='Is PC')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Is Bot')),
                ('browser_family', models.CharField(blank=True, max_length=150, null=True, verbose_name='Browser Name')),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Browser OS')),
                ('os_family', models.CharField(blank=True, max_length=150, null=True, verbose_name='OS Family')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='OS Version')),
                ('device_family', models.CharField(blank=True, max_length=150, null=True, verbose_name='Device')),
            ],
            options={
                'verbose_name': 'API Logs',
                'verbose_name_plural': 'API Log',
                'ordering': ('-created_at',),
            },
        ),
    ]
