# Generated by Django 5.1.3 on 2025-07-06 11:44

import appointments.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjective", models.CharField(max_length=255)),
                ("cc", models.CharField(max_length=255)),
                ("allergies", models.CharField(blank=True, max_length=255, null=True)),
                ("vitals", models.CharField(blank=True, max_length=255, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_notes",
                        to=settings.AUTH_USER_MODEL,
                        validators=[appointments.validators.validate_doctor],
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_notes",
                        to=settings.AUTH_USER_MODEL,
                        validators=[appointments.validators.validate_patient],
                        verbose_name="Patient",
                    ),
                ),
            ],
        ),
    ]
