# Generated by Django 5.1.3 on 2025-05-21 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disease", models.CharField(max_length=255)),
                ("pharmacy_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Must be a user with doctor role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Must be a user with patient role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=100)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescription.prescription",
                    ),
                ),
            ],
        ),
    ]
