# Generated by Django 5.1.3 on 2025-05-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prescriptionitem",
            options={"ordering": ("medicine_name",)},
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="date_started",
            field=models.DateField(
                blank=True, help_text="When patient began this medication", null=True
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="days_supply",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many days the dispensed supply will last",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="quantity_dispensed",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total units (pills/capsules) dispensed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="refill_threshold_days",
            field=models.PositiveIntegerField(
                default=3, help_text="Notify this many days before supply runs out"
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="refills_allowed",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this prescription may be refilled"
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="refills_remaining",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of refills still available"
            ),
        ),
    ]
