# Generated by Django 5.1.3 on 2025-06-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0002_alter_prescriptionitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prescriptionitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="date_started",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="days_supply",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="quantity_dispensed",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="refill_threshold_days",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="refills_allowed",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="refills_remaining",
        ),
    ]
