# Generated by Django 5.1.3 on 2025-06-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPTCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "CPT Code",
                "verbose_name_plural": "CPT Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ICDCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "ICD Code",
                "verbose_name_plural": "ICD Codes",
                "ordering": ["code"],
            },
        ),
    ]
