# Generated by Django 5.1.3 on 2024-11-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_hospital_hospital_rating"),
        ("user", "0002_alter_customuser_country_alter_customuser_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="hospital.hospital",
                verbose_name="Hospital",
            ),
        ),
    ]
