# Generated by Django 5.1.3 on 2024-11-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0004_userpermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpermission",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "User Permission",
                "verbose_name_plural": "User Permissions",
            },
        ),
        migrations.AddField(
            model_name="userpermission",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Related Model",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
