# Generated by Django 5.1.3 on 2024-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_userpermission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="change_password",
            field=models.BooleanField(default=False, verbose_name="Change Password"),
        ),
    ]
