# Generated by Django 5.1.3 on 2025-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_customuser_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                null=True,
                verbose_name="Blood Group",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="disease",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Disease"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height_feet",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Height (Feet)"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height_inches",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Height (Inches)"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Weight (Grams)"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight_kilo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Weight (Kilo)"
            ),
        ),
    ]
