# Generated by Django 5.1.3 on 2024-11-24 19:08

import django.core.validators
import hospital.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="hospital_rating",
            field=models.FloatField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    hospital.validators.validate_hospital_rating,
                ],
                verbose_name="Hospital Rating",
            ),
        ),
    ]
