# Generated by Django 5.1.3 on 2024-11-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_hospital_hospital_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital",
            old_name="facilites",
            new_name="facilities",
        ),
    ]
