# Generated by Django 5.1.3 on 2024-12-27 18:35

import base.base_upload_handlers
import base.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recording_ai_voice_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Recording AI Voice Note"
                    ),
                ),
                (
                    "recording_ai_voice_note_status",
                    models.CharField(
                        choices=[("ACCEPTED", "Accepted"), ("REJECTED", "Rejected")],
                        default="REJECTED",
                        verbose_name="Recording AI Voice Note Status",
                    ),
                ),
                (
                    "is_started",
                    models.BooleanField(default=False, verbose_name="Is Started"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Is Finished"),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Follow Up Date"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation",
                "verbose_name_plural": "Consultations",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ConsultationRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recording_audio",
                    models.FileField(
                        upload_to=base.base_upload_handlers.handle_consultation_recording,
                        validators=[
                            base.base_upload_handlers.handle_consultation_recording_upload_limit,
                            base.utils.validate_consultation_recording_extension,
                        ],
                        verbose_name="Recording",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_recordings",
                        to="consultation.consultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Recording",
                "verbose_name_plural": "Consultation Recordings",
                "ordering": ("-created_at",),
            },
        ),
    ]
