# Generated by Django 5.1.3 on 2025-07-04 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationrecording",
            name="ai_response",
            field=models.TextField(
                blank=True,
                help_text="AI-generated response based on the transcription",
                null=True,
                verbose_name="AI Response",
            ),
        ),
        migrations.AddField(
            model_name="consultationrecording",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when AI processing was completed",
                null=True,
                verbose_name="Processed At",
            ),
        ),
        migrations.AddField(
            model_name="consultationrecording",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who initiated the AI processing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Processed By",
            ),
        ),
        migrations.AddField(
            model_name="consultationrecording",
            name="processing_error",
            field=models.TextField(
                blank=True,
                help_text="Error message if AI processing failed",
                null=True,
                verbose_name="Processing Error",
            ),
        ),
        migrations.AddField(
            model_name="consultationrecording",
            name="transcription",
            field=models.TextField(
                blank=True,
                help_text="AI-generated text transcription of the audio recording",
                null=True,
                verbose_name="Transcription",
            ),
        ),
    ]
