# Generated by Django 5.1.3 on 2025-07-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0002_consultationrecording_ai_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultationrecording",
            name="ai_response",
        ),
        migrations.RemoveField(
            model_name="consultationrecording",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="consultationrecording",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="consultationrecording",
            name="processing_error",
        ),
        migrations.RemoveField(
            model_name="consultationrecording",
            name="transcription",
        ),
    ]
